(dirs
 wisl
 GillianCore
 Gillian-JS
 Gillian-C
 Gillian-C2
 transformers
 Gillian-Alcotest-Runner
 ppx_sat)

(env
 (static
  (flags
   (:standard -w -67 -w -69 -w -70))
  (link_flags
   (:standard -ccopt -static)))
 (opt
  (ocamlopt_flags
   (:standard -O3)))
 (_
  (flags
   (:standard -w -67 -w -69 -w -70))))
