#!/bin/bash

set -euo pipefail

if command -v opam >/dev/null 2>&1; then
  echo "[INFO] Running source code formatting"
  opam exec -- dune fmt

  echo "[INFO] Running build"
  opam exec -- dune build
  exit 0
else
  echo >&2 "[ERR] Failed precommit validation: opam isn't available"
  exit 1
fi