#!/bin/bash

set -euo pipefail

if command -v opam >/dev/null 2>&1; then
  echo "[INFO] Running source code formatting"
  opam exec -- dune fmt

  echo "[INFO] Running build"
  opam exec -- dune build
  exit 0
else
  echo >&2 "[ERR] Failed precommit validation: opam isn't available"
  exit 1
fi

if command -v make >/dev/null 2>&1; then
  echo "[INFO] Checking makefile"
  make -n > /dev/null
else
  echo >&2 "[ERR] Failed makefile check: make isn't installed"
fi

# Code that checks if any file of the form *.opam has active diffs and exits with 1 if there is one
if git diff --name-only | grep -qE '\.opam$'; then
  echo >&2 "[ERR] Failed precommit validation: opam files have active diffs, probably triggered by the build steps"
  exit 1
fi