# syntax=docker/dockerfile:1

FROM ocaml/opam:debian-13-ocaml-5.3
RUN sudo apt-get update
RUN sudo apt-get install libgmp-dev pkg-config libsqlite3-dev python3 z3 -y
WORKDIR /home/opam/app/Gillian
COPY --exclude=./_opam --exclude=**/_build . .
RUN sudo chown -R opam:opam .
RUN [ ! -f .docker_opam_cache ] || mv .docker_opam_cache ~/.opam/5.3
RUN opam update -y
RUN opam install . --deps-only
RUN opam exec -- dune build @all

