# syntax=docker/dockerfile:1

FROM ubuntu:noble
ARG no_cbmc=
ADD https://github.com/diffblue/cbmc/releases/download/cbmc-6.9.0/ubuntu-24.04-cbmc-6.9.0-Linux.deb cbmc.deb
RUN apt update \
    && apt install -y z3 $([ $no_cbmc ] || echo './cbmc.deb') \
    && rm -rf /var/lib/apt/lists/* cbmc.deb
# Artifacts lose their exec bits.
COPY --chmod=755 bin/ /usr/local/bin/
