#!/usr/bin/env python3
"""Re-apply Gillian's local additions to a freshly vendored copy of CSE's
OCaml library.

CSE (~/dev/CSE) is the source of truth for the verified encoder.  Gillian needs
three things CSE deliberately does not have, because they are Gillian-specific
and are not part of the verified development:

  * the GIL values `none`, `empty` and `loc`, as constructors of the SMT `Val`
    datatype, together with their type tests and coercions;
  * the matching `Type.t` / `Val.t` constructors in the hand-written wrappers;
  * the `declare-datatype` entries that announce them to the solver.

The first of those is an addition to *extracted* code, so it cannot be a source
edit in CSE and it is not regenerated by extraction.  This script re-applies all
of it after `vendor.sh` has copied CSE over the top.

Each addition is anchored on the corresponding `null` declaration, which is the
sibling of every Gillian value added here and is stable across CSE releases.
An anchor that no longer matches exactly once is a hard error: the tool refuses
to guess.  Re-vendoring is therefore safe to repeat, and never silently
half-applies.

Usage:  local_additions.py [vendored-dir]      (default: ../../GillianCore/cse)
"""

import sys
from pathlib import Path

# Every addition mentions "gillian", which is how we detect a file that has
# already been patched.
MARKER = "gillian"

# (relative path, mode, anchor, note, payload).  Payload text is verbatim: it is
# split on newlines with no trimming, so a trailing blank line is significant.
#
#   after_line   insert directly after the anchor line
#   after_block  insert after the blank line that terminates the anchor's block
#   after_arm    insert before the next match arm starting in column 0
EDITS = [
    (
        """extracted/extracted.mli""",
        """after_line""",
        """| PVNull""",
        """preval constructors""",
        """| PVGillianNone
| PVGillianEmpty
| PVGillianLoc of int""",
    ),
    (
        """extracted/extracted.mli""",
        """after_line""",
        """| TNull""",
        """type0 constructors""",
        """| TGillianNone
| TGillianEmpty
| TGillianLoc""",
    ),
    (
        """extracted/extracted.mli""",
        """after_block""",
        """val c_null_val : identifier""",
        """constructor identifiers""",
        """val c_gillian_none_val : identifier

val c_gillian_empty_val : identifier

val c_gillian_loc_val : identifier
""",
    ),
    (
        """extracted/extracted.mli""",
        """after_block""",
        """val null_val : term""",
        """term builders""",
        """val gillian_none_val : term

val gillian_empty_val : term

val gillian_loc_val : term -> term
""",
    ),
    (
        """extracted/extracted.mli""",
        """after_block""",
        """val g_null_val : identifier""",
        """getter identifier""",
        """val g_gillian_loc_val : identifier
""",
    ),
    (
        """extracted/extracted.mli""",
        """after_block""",
        """val p_null_val : identifier""",
        """predicate identifiers""",
        """val p_gillian_none_val : identifier

val p_gillian_empty_val : identifier

val p_gillian_loc_val : identifier
""",
    ),
    (
        """extracted/extracted.mli""",
        """after_block""",
        """val is_null_val : term -> term""",
        """predicates""",
        """val is_gillian_none_val : term -> term

val is_gillian_empty_val : term -> term

val is_gillian_loc_val : term -> term
""",
    ),
    (
        """extracted/extracted.mli""",
        """after_block""",
        """val to_null :""",
        """coercions""",
        """val to_gillian_value :
  (term -> term) ->
  ((term * sort) * term gset ->
  ((term * sort) * term gset) option)

val to_gillian_none :
  ((term * sort) * term gset) -> ((term * sort) * term gset) option

val to_gillian_empty :
  ((term * sort) * term gset) -> ((term * sort) * term gset) option

val to_gillian_loc :
  ((term * sort) * term gset) -> ((term * sort) * term gset) option
""",
    ),
    (
        """extracted/extracted.ml""",
        """after_line""",
        """| PVNull""",
        """preval constructors""",
        """| PVGillianNone
| PVGillianEmpty
| PVGillianLoc of int""",
    ),
    (
        """extracted/extracted.ml""",
        """after_line""",
        """| TNull""",
        """type0 constructors""",
        """| TGillianNone
| TGillianEmpty
| TGillianLoc""",
    ),
    (
        """extracted/extracted.ml""",
        """after_line""",
        """| TNull -> _UU03c3__null""",
        """encode_type arms""",
        """| TGillianNone -> _UU03c3__val
| TGillianEmpty -> _UU03c3__val
| TGillianLoc -> _UU03c3__val""",
    ),
    (
        """extracted/extracted.ml""",
        """after_block""",
        """let c_null_val =""",
        """constructor identifiers""",
        """(** val c_gillian_none_val : identifier **)

let c_gillian_none_val =
  IdSimple ('n'::('o'::('n'::('e'::[]))))

(** val c_gillian_empty_val : identifier **)

let c_gillian_empty_val =
  IdSimple ('e'::('m'::('p'::('t'::('y'::[])))))

(** val c_gillian_loc_val : identifier **)

let c_gillian_loc_val =
  IdSimple ('l'::('o'::('c'::[])))
""",
    ),
    (
        """extracted/extracted.ml""",
        """after_block""",
        """let null_val =""",
        """term builders""",
        """(** val gillian_none_val : term **)

let gillian_none_val =
  TApp (c_gillian_none_val, None, [])

(** val gillian_empty_val : term **)

let gillian_empty_val =
  TApp (c_gillian_empty_val, None, [])

(** val gillian_loc_val : term -> term **)

let gillian_loc_val t =
  TApp (c_gillian_loc_val, None, (t :: []))
""",
    ),
    (
        """extracted/extracted.ml""",
        """after_block""",
        """let g_null_val =""",
        """getter identifier""",
        """(** val g_gillian_loc_val : identifier **)

let g_gillian_loc_val =
  IdSimple ('g'::('e'::('t'::('L'::('o'::('c'::[]))))))
""",
    ),
    (
        """extracted/extracted.ml""",
        """after_block""",
        """let p_null_val =""",
        """predicate identifiers""",
        """(** val p_gillian_none_val : identifier **)

let p_gillian_none_val =
  identifier_add_prefix ('i'::('s'::('-'::[]))) c_gillian_none_val

(** val p_gillian_empty_val : identifier **)

let p_gillian_empty_val =
  identifier_add_prefix ('i'::('s'::('-'::[]))) c_gillian_empty_val

(** val p_gillian_loc_val : identifier **)

let p_gillian_loc_val =
  identifier_add_prefix ('i'::('s'::('-'::[]))) c_gillian_loc_val
""",
    ),
    (
        """extracted/extracted.ml""",
        """after_block""",
        """let is_null_val t =""",
        """predicates""",
        """(** val is_gillian_none_val : term -> term **)

let is_gillian_none_val t =
  TApp (p_gillian_none_val, None, (t :: []))

(** val is_gillian_empty_val : term -> term **)

let is_gillian_empty_val t =
  TApp (p_gillian_empty_val, None, (t :: []))

(** val is_gillian_loc_val : term -> term **)

let is_gillian_loc_val t =
  TApp (p_gillian_loc_val, None, (t :: []))
""",
    ),
    (
        """extracted/extracted.ml""",
        """after_line""",
        """  | TNull -> is_null_val t""",
        """is_type arms""",
        """  | TGillianNone -> is_gillian_none_val t
  | TGillianEmpty -> is_gillian_empty_val t
  | TGillianLoc -> is_gillian_loc_val t""",
    ),
    (
        """extracted/extracted.ml""",
        """after_block""",
        """let to_null = function""",
        """coercions""",
        """(** val to_gillian_value :
    (term -> term) -> ((term * sort) * term gset) -> ((term * sort) * term
    gset) option **)

let to_gillian_value tester = function
| (p, _UU03a6_) ->
  let (t, _UU03c3_) = p in
  let t_some = get_some_val t in
  let cases =
    insert0 (map_insert (gmap_partial_alter sort_eq_decision sort_countable))
      _UU03c3__val ((t, _UU03c3__val),
      (union0 (gset_union term_eq_decision term_countable) _UU03a6_
        (singleton0 (gset_singleton term_eq_decision term_countable)
          (tester t))))
      (singletonM0
        (map_singleton (gmap_partial_alter sort_eq_decision sort_countable)
          (gmap_empty sort_eq_decision sort_countable)) _UU03c3__maybe_val
        ((t_some, _UU03c3__val),
        (union0 (gset_union term_eq_decision term_countable)
          (union0 (gset_union term_eq_decision term_countable) _UU03a6_
            (singleton0 (gset_singleton term_eq_decision term_countable)
              (is_some_val t)))
          (singleton0 (gset_singleton term_eq_decision term_countable)
            (tester t_some)))))
  in
  lookup0 (gmap_lookup sort_eq_decision sort_countable) _UU03c3_ cases

(** val to_gillian_none :
    ((term * sort) * term gset) -> ((term * sort) * term gset) option **)

let to_gillian_none =
  to_gillian_value is_gillian_none_val

(** val to_gillian_empty :
    ((term * sort) * term gset) -> ((term * sort) * term gset) option **)

let to_gillian_empty =
  to_gillian_value is_gillian_empty_val

(** val to_gillian_loc :
    ((term * sort) * term gset) -> ((term * sort) * term gset) option **)

let to_gillian_loc =
  to_gillian_value is_gillian_loc_val
""",
    ),
    (
        """extracted/extracted.ml""",
        """after_line""",
        """  | TNull -> to_null ((t, _UU03c3_), _UU03a6_)""",
        """to_type arms""",
        """  | TGillianNone -> to_gillian_none ((t, _UU03c3_), _UU03a6_)
  | TGillianEmpty -> to_gillian_empty ((t, _UU03c3_), _UU03a6_)
  | TGillianLoc -> to_gillian_loc ((t, _UU03c3_), _UU03a6_)""",
    ),
    (
        """extracted/extracted.ml""",
        """after_arm""",
        """| PVNull ->""",
        """encode_preval arms""",
        """| PVGillianNone ->
  Some ((gillian_none_val, _UU03c3__val),
    (empty0 (gset_empty term_eq_decision term_countable)))
| PVGillianEmpty ->
  Some ((gillian_empty_val, _UU03c3__val),
    (empty0 (gset_empty term_eq_decision term_countable)))
| PVGillianLoc i ->
  let rec positive_of_int n0 =
    if n0 <= 1 then XH
    else
      let q = n0 / 2 in
      if n0 mod 2 = 0 then XO (positive_of_int q) else XI (positive_of_int q)
  in
  let z = if i <= 0 then Z0 else Zpos (positive_of_int i) in
  Some (((gillian_loc_val (int_literal z)), _UU03c3__val),
    (empty0 (gset_empty term_eq_decision term_countable)))""",
    ),
    (
        """syntax/type.mli""",
        """after_line""",
        """| Null""",
        """Gillian type constructors""",
        """| None
| Empty
| Loc""",
    ),
    (
        """syntax/type.ml""",
        """after_line""",
        """| Null""",
        """Gillian type constructors""",
        """| None
| Empty
| Loc""",
    ),
    (
        """syntax/type.ml""",
        """after_line""",
        """  | Null -> Extracted.TNull""",
        """Gillian type extraction""",
        """  | None -> Extracted.TGillianNone
  | Empty -> Extracted.TGillianEmpty
  | Loc -> Extracted.TGillianLoc""",
    ),
    (
        """syntax/val.mli""",
        """after_line""",
        """| Null""",
        """Gillian value constructors""",
        """| None
| Empty
| Loc of int""",
    ),
    (
        """syntax/val.ml""",
        """after_line""",
        """| Null""",
        """Gillian value constructors""",
        """| None
| Empty
| Loc of int""",
    ),
    (
        """syntax/val.ml""",
        """after_line""",
        """  | Null -> Extracted.PVNull""",
        """Gillian value extraction""",
        """  | None -> Extracted.PVGillianNone
  | Empty -> Extracted.PVGillianEmpty
  | Loc i -> Extracted.PVGillianLoc i""",
    ),
    (
        """smt/smt.ml""",
        """after_line""",
        """                 Sexp.List [atom Extracted.g_null_val; atom Extracted.s_null]];""",
        """Gillian constructors in the sigma_val datatype""",
        """                Sexp.List [atom Extracted.c_gillian_none_val];
                Sexp.List [atom Extracted.c_gillian_empty_val];
                Sexp.List
                  [atom Extracted.c_gillian_loc_val;
                   Sexp.List [atom Extracted.g_gillian_loc_val; atom Extracted.s_int]];""",
    ),
]

# Identifiers that must exist once the additions are in place.  This is the
# post-condition: it catches an edit that landed in the wrong place as well as
# one that did not land at all.
EXPECTED = {
    "extracted/extracted.mli": [
        "PVGillianNone", "PVGillianEmpty", "PVGillianLoc",
        "TGillianNone", "TGillianEmpty", "TGillianLoc",
        "c_gillian_none_val", "c_gillian_empty_val", "c_gillian_loc_val",
        "gillian_none_val", "gillian_empty_val", "gillian_loc_val",
        "g_gillian_loc_val",
        "p_gillian_none_val", "p_gillian_empty_val", "p_gillian_loc_val",
        "is_gillian_none_val", "is_gillian_empty_val", "is_gillian_loc_val",
        "to_gillian_value", "to_gillian_none", "to_gillian_empty",
        "to_gillian_loc",
    ],
    "extracted/extracted.ml": [
        "PVGillianNone", "PVGillianEmpty", "PVGillianLoc",
        "TGillianNone", "TGillianEmpty", "TGillianLoc",
        "c_gillian_none_val", "gillian_none_val", "g_gillian_loc_val",
        "p_gillian_none_val", "is_gillian_none_val", "to_gillian_value",
        "to_gillian_none", "to_gillian_empty", "to_gillian_loc",
    ],
    "syntax/type.ml": ["TGillianNone", "TGillianEmpty", "TGillianLoc"],
    "syntax/type.mli": ["Empty"],
    "syntax/val.ml": ["PVGillianNone", "PVGillianEmpty", "PVGillianLoc"],
    "syntax/val.mli": ["Loc of int"],
    "smt/smt.ml": ["c_gillian_none_val", "c_gillian_loc_val",
                   "g_gillian_loc_val"],
}

# Vendored .ml files that reference the utils library.  CSE builds it as `utils`
# (so the module is `Utils`); Gillian must rename it to `extraction_utils` to
# avoid colliding with GillianCore's own `utils`, which wraps it as
# `Extraction_utils.Utils`.  Opening the wrapper restores the `Utils.` prefix
# the copied sources use.
UTILS_OPEN = "open Extraction_utils"


class Failed(Exception):
    pass


def find_unique(lines, anchor, path):
    hits = [i for i, l in enumerate(lines) if l == anchor]
    if len(hits) != 1:
        raise Failed(
            f"{path}: anchor matched {len(hits)} times, expected exactly one\n"
            f"  anchor: {anchor!r}\n"
            f"  CSE's generated code has moved; re-roll this edit by hand."
        )
    return hits[0]


def insertion_point(lines, mode, at, path, anchor):
    if mode == "after_line":
        return at + 1
    if mode == "after_block":
        j = at
        while j < len(lines) and lines[j].strip() != "":
            j += 1
        if j == len(lines):
            raise Failed(f"{path}: no blank line ends the block at {anchor!r}")
        return j + 1
    if mode == "after_arm":
        j = at + 1
        while j < len(lines) and not lines[j].startswith("|"):
            j += 1
        if j == len(lines):
            raise Failed(f"{path}: no following match arm after {anchor!r}")
        return j
    raise Failed(f"unknown mode {mode!r}")


def main(argv):
    root = Path(argv[1]) if len(argv) > 1 else Path(__file__).resolve().parents[2] / "GillianCore" / "cse"
    if not root.is_dir():
        raise Failed(f"no such vendored directory: {root}")

    # Refuse to patch anything twice: vendor.sh always copies clean files first.
    for rel in sorted({e[0] for e in EDITS}):
        text = (root / rel).read_text()
        if MARKER in text.lower():
            raise Failed(
                f"{rel} already contains Gillian additions.\n"
                f"  Run vendor.sh, which copies clean files from CSE first."
            )

    by_file = {}
    for rel, mode, anchor, note, payload in EDITS:
        by_file.setdefault(rel, []).append((mode, anchor, note, payload))

    for rel, edits in by_file.items():
        path = root / rel
        lines = path.read_text().split("\n")
        # Apply bottom-up so earlier insertions cannot shift later anchors.
        located = []
        for mode, anchor, note, payload in edits:
            at = find_unique(lines, anchor, rel)
            located.append((insertion_point(lines, mode, at, rel, anchor), payload, note))
        for point, payload, _note in sorted(located, key=lambda x: -x[0]):
            lines[point:point] = payload.split("\n")
        path.write_text("\n".join(lines))
        print(f"  {rel}: {len(edits)} additions")

    # The utils library rename.
    for path in sorted(root.rglob("*.ml")):
        text = path.read_text()
        if "Utils." in text and UTILS_OPEN not in text:
            path.write_text(UTILS_OPEN + "\n\n" + text)
            print(f"  {path.relative_to(root)}: + {UTILS_OPEN}")

    # Post-conditions.
    problems = []
    for rel, names in EXPECTED.items():
        text = (root / rel).read_text()
        missing = [n for n in names if n not in text]
        if missing:
            problems.append(f"{rel}: missing {', '.join(missing)}")
    if problems:
        raise Failed("additions did not land:\n  " + "\n  ".join(problems))

    print(f"applied {len(EDITS)} additions across {len(by_file)} files; all post-conditions hold")


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv) or 0)
    except Failed as e:
        print(f"error: {e}", file=sys.stderr)
        sys.exit(1)
