(menhir
 (modules annot_parser)
 (flags --explain))

(ocamllex
 (modules annot_lexer))

(library
 (name cgil_lib)
 (public_name gillian-c.cgil_lib)
 (libraries
  gillian
  gillian.alcotest-runner
  compcert
  printbox-text
  gillian.ppx_sat.runtime
  ppx_deriving_yojson.runtime)
 (preprocess
  (pps ppx_deriving.std ppx_deriving_yojson gillian.ppx_sat))
 (instrumentation
  (backend landmarks --auto)))

(rule
 (target runtime_files.ml)
 (deps
  (source_tree ../runtime))
 (action
  (run ocaml-crunch -s -m plain -e gil ../runtime -o %{target})))

(rule
 (target include_files.ml)
 (deps
  (source_tree ../includes))
 (action
  (run ocaml-crunch -s -m plain -e h ../includes -o %{target})))
