name: Light

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - '!master'

jobs:
  build:
    strategy:
      matrix:
        operating-system: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Installing esy
      run: npm install -g esy@0.6.2 --unsafe-perm
    - name: Restore Cache
      id: restore-cache
      uses: actions/cache@v1
      with:
        path: _export
        key:  ${{ runner.os }}-esy-${{ hashFiles('esy.lock/index.json') }}
        restore-keys: |
          ${{ runner.os }}-esy-
    - name: Esy install
      run: 'esy install'
    - name: Import Cache
      run: |
        esy import-dependencies _export
        rm -rf _export
    - name: Esy build
      run: 'esy build'
      id: esy-build
    - name: Format checking
      run: 'esy format-check'
    - name: Building release
      run: 'esy release'
    - name: Sending artifact for next jobs
      uses: actions/upload-artifact@v1
      with:
        name: ${{ runner.os }}-release
        path: _release
    - name: Setting dependency cache
      run: |
        esy cleanup .
        esy export-dependencies
      if: steps.restore-cache.outputs.cache-hit != 'true'

  gillian_c_tests:
    strategy:
      matrix:
        operating-system: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.operating-system }}
    needs: build
    steps:
      - name: download release
        uses: actions/download-artifact@v1
        with:
          name: ${{ runner.os }}-release
          path: release
      - name: setting up node
        uses: actions/setup-node@v1
      - name: install release
        run: npm install -g ./release
      - name: checkout project
        uses: actions/checkout@v2
        with:
          path: Gillian
      - name: init env
        run: 'Gillian-C/scripts/setup_environment.sh'
        working-directory: 'Gillian'
      - name: Test All
        run: './testAll.sh'
        working-directory: 'Gillian/Gillian-C/environment/'
  
  gillian_js_tests:
    strategy:
      matrix:
        operating-system: [ macos-latest, ubuntu-latest ]
    runs-on: ${{ matrix.operating-system }}
    needs: build
    steps:
      - name: download release
        uses: actions/download-artifact@v1
        with:
          name: ${{ runner.os }}-release
          path: release
      - name: setting up node
        uses: actions/setup-node@v1
      - name: install release
        run: npm install -g ./release
      - name: checkout project
        uses: actions/checkout@v2
        with:
          path: Gillian
      - name: init env
        run: 'Gillian-JS/scripts/setup_environment.sh'
        working-directory: 'Gillian'
      - name: Test JaVerT
        run: './testJaVerT.sh'
        working-directory: 'Gillian/Gillian-JS/environment/'